const KEY = 'skladon-data';
const initial = {products:[],
  sales:[], movements:[], debts:[], returns:[], activity:[], sellerAccount:null};
let data = JSON.parse(localStorage.getItem(KEY) || 'null') || JSON.parse(JSON.stringify(initial));
const persist = () => { try { localStorage.setItem(KEY, JSON.stringify(data)); return true; } catch (error) { alert('Не удалось сохранить данные. Освободите место в браузере или скачайте резервную копию.'); return false; } };
const demoIds = new Set(['p1', 'p2', 'p3']);
if (data.products.some(p => demoIds.has(p.id))) {
  data.products = data.products.filter(p => !demoIds.has(p.id));
  data.movements = data.movements.filter(m => !['Молоко 3.2%', 'Хлеб ржано-пшеничный', 'Чай чёрный 25 пакетов'].includes(m.name));
  data.sales = data.sales.filter(s => !s.items.some(i => demoIds.has(i.id)));
  persist();
}
data.products.forEach(p => { p.cost = Number(p.cost) || 0; p.price = Number(p.price) || 0; p.minPrice = Number(p.minPrice ?? p.cost) || 0; });
data.products.forEach(p => { p.type = p.type || ''; p.model = p.model || ''; });
data.debts = Array.isArray(data.debts) ? data.debts : [];
data.returns = Array.isArray(data.returns) ? data.returns : [];
data.activity = Array.isArray(data.activity) ? data.activity : [];
data.debts.forEach(d => { d.paid = d.paid === true; });
if (!Object.prototype.hasOwnProperty.call(data, 'sellerAccount')) data.sellerAccount = null;
let page = 'dashboard', saleCart = [];
const money = n => `${new Intl.NumberFormat('ru-RU',{maximumFractionDigits:0}).format(n||0)} сум`;
const save = () => persist();
const esc = s => String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today = () => new Date().toLocaleDateString('ru-RU');
const isoToday = () => new Date().toISOString().slice(0, 10);
const debtState = debt => debt.paid ? 'paid' : debt.dueDate < isoToday() ? 'overdue' : 'pending';
function layout(content,title){document.querySelector('#app').innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand">Skladon<small>офлайн-учёт склада</small></div><div class="nav">${nav('dashboard','Дашборд','▦')}${nav('products','Товары','□')}${nav('sales','Продажи','сум')}${nav('movements','Движения','↕')}${nav('settings','Настройки','⚙')}</div></aside><main class="main"><div class="topbar"><div><h1>${title}</h1><span class="muted">Данные сохраняются на этом устройстве</span></div>${page==='products'?'<button class="btn" onclick="openProduct()">＋ Добавить товар</button>':''}</div>${content}</main><nav class="mobile-nav">${nav('dashboard','Главная','⌂')}${nav('products','Товары','□')}${nav('sales','Продажи','сум')}${nav('movements','Склад','↕')}</nav></div>`}
function nav(id,text,icon){return `<button class="${page===id?'active':''}" onclick="go('${id}')">${icon} &nbsp;${text}</button>`}
function go(p){page=p;render()}
function render(){if(page==='dashboard')dashboard(); if(page==='products')products(); if(page==='sales')sales(); if(page==='movements')movements(); if(page==='settings')settings()}
function dashboard(){const revenue=data.sales.reduce((s,x)=>s+x.total,0), profit=data.sales.reduce((s,x)=>s+x.profit,0), low=data.products.filter(x=>x.stock<=x.min), openDebts=data.debts.filter(x=>!x.paid), overdue=openDebts.filter(x=>debtState(x)==='overdue');layout(`<section class="cards"><div class="card"><span class="muted">Выручка сегодня</span><div class="metric teal">${money(revenue)}</div><span class="muted">${data.sales.length} продаж</span></div><div class="card"><span class="muted">Прибыль</span><div class="metric">${money(profit)}</div><span class="muted">по проведённым продажам</span></div><div class="card"><span class="muted">Долги клиентов</span><div class="metric ${overdue.length?'':'teal'}">${money(openDebts.reduce((s,x)=>s+x.amount,0))}</div><span class="muted">${overdue.length} просрочено</span></div><div class="card"><span class="muted">Низкий остаток</span><div class="metric ${low.length?'':'teal'}">${low.length}</div><span class="muted">требуют внимания</span></div></section><div class="grid"><div class="panel"><h2>Долги с ближайшим возвратом</h2>${openDebts.length?openDebts.slice().sort((a,b)=>a.dueDate.localeCompare(b.dueDate)).slice(0,5).map(x=>`<div style="display:flex;justify-content:space-between;padding:11px 0;border-bottom:1px solid #edf2f1"><span><b>${esc(x.customer)}</b><br><span class="muted">до ${esc(x.dueDate)}</span></span><span class="badge ${debtState(x)==='overdue'?'red':'warn'}">${money(x.amount)}</span></div>`).join(''):'<div class="empty">Открытых долгов нет ✓</div>'}</div><div class="panel"><h2>Нужно пополнить</h2>${low.length?low.map(x=>`<div style="display:flex;justify-content:space-between;padding:11px 0;border-bottom:1px solid #edf2f1"><span>${esc(x.name)}</span><span class="badge red">${x.stock} ${x.unit}</span></div>`).join(''):'<div class="empty">Все остатки в норме ✓</div>'}</div></div>`,'Дашборд')}
function products(){layout(`<div class="panel"><div class="toolbar"><input id="product-search" class="search" placeholder="Поиск по названию, артикулу..." oninput="filterProducts()"><span class="muted">${data.products.length} товаров</span></div><div class="table-wrap"><table><thead><tr><th>Товар</th><th>Категория</th><th>Себестоимость</th><th>Продажа / минимум</th><th>Остаток</th><th></th></tr></thead><tbody id="product-rows">${productRows(data.products)}</tbody></table></div></div>`,'Товары')}
function productRows(list){return list.length?list.map(x=>`<tr><td><b>${esc(x.name)}</b><br><span class="muted">${esc(x.sku)} · ${esc(x.unit)}</span></td><td>${esc(x.category||'—')}</td><td>${money(x.cost)}</td><td>${money(x.price)}<br><span class="muted">мин. ${money(x.minPrice)}</span></td><td><span class="badge ${x.stock<=x.min?'red':''}">${x.stock} ${x.unit}</span></td><td><button class="btn secondary" onclick="openMovement('${x.id}')">Изменить остаток</button> <button class="btn danger" onclick="deleteProduct('${x.id}')">Удалить</button></td></tr>`).join(''):'<tr><td colspan="6"><div class="empty">Ничего не найдено</div></td></tr>'}
function filterProducts(){const q=document.querySelector('#product-search').value.toLowerCase();document.querySelector('#product-rows').innerHTML=productRows(data.products.filter(x=>(x.name+x.sku+x.category).toLowerCase().includes(q)))}
function sales(){layout(`<div class="panel"><div class="toolbar"><div><h2>Продажи</h2><span class="muted">Оформляйте продажи даже без интернета</span></div><button class="btn" onclick="openSale()">＋ Новая продажа</button></div>${data.sales.length?`<div class="table-wrap"><table><thead><tr><th>Номер</th><th>Дата</th><th>Товаров</th><th>Сумма</th><th>Оплата</th><th>Прибыль</th><th></th></tr></thead><tbody>${data.sales.slice().reverse().map(x=>`<tr><td>#${x.id.slice(-5)}</td><td>${x.date}</td><td>${x.items.map(i=>esc(i.name)).join(', ')}</td><td><b>${money(x.total)}</b></td><td>${x.credit?'В долг':'Оплачено'}</td><td>${money(x.profit)}</td><td><button class="btn secondary" onclick="openReturn('${x.id}')">Возврат</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Продажи появятся здесь после оформления.</div>'}</div><div class="panel" style="margin-top:18px"><h2>Долги клиентов</h2>${data.debts.length?`<div class="table-wrap"><table><thead><tr><th>Должник</th><th>Контакты</th><th>Продажа</th><th>Вернуть до</th><th>Статус</th><th></th></tr></thead><tbody>${data.debts.slice().reverse().map(x=>`<tr><td><b>${esc(x.customer)}</b></td><td>${x.phone?`☎ ${esc(x.phone)}<br>`:''}${x.address?`<span class="muted">${esc(x.address)}</span>`:''}</td><td>${money(x.amount)}</td><td>${esc(x.dueDate)}</td><td><span class="badge ${x.paid?'':'red'}">${x.paid?'Погашен':debtState(x)==='overdue'?'Просрочен':'Ожидается'}</span></td><td>${x.paid?'':`<button class="btn secondary" onclick="markDebtPaid('${x.id}')">Отметить оплату</button>`}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Продаж в долг пока нет.</div>'}</div>`,'Продажи')}
function movements(){const units=data.products.reduce((s,x)=>s+(Number(x.stock)||0),0),costValue=data.products.reduce((s,x)=>s+(Number(x.stock)||0)*(Number(x.cost)||0),0),saleValue=data.products.reduce((s,x)=>s+(Number(x.stock)||0)*(Number(x.price)||0),0);layout(`<div class="cards"><div class="card"><span class="muted">Позиций товаров</span><div class="metric teal">${data.products.length}</div></div><div class="card"><span class="muted">Всего единиц</span><div class="metric">${units}</div></div><div class="card"><span class="muted">Себестоимость склада</span><div class="metric">${money(costValue)}</div></div><div class="card"><span class="muted">Стоимость продажи</span><div class="metric">${money(saleValue)}</div></div></div><div class="panel" style="margin-top:18px"><div class="toolbar"><div><h2>Общие остатки товаров</h2><span class="muted">Сводка по текущему складу</span></div><button class="btn" onclick="printInventory()">Сохранить остатки в PDF</button></div>${data.products.length?`<div class="table-wrap"><table><thead><tr><th>№</th><th>Артикул</th><th>Товар</th><th>Категория</th><th>Остаток</th><th>Себестоимость</th><th>Стоимость</th></tr></thead><tbody>${data.products.map((x,i)=>`<tr><td>${i+1}</td><td>${esc(x.sku)}</td><td><b>${esc(x.name)}</b></td><td>${esc(x.category||'—')}</td><td><span class="badge ${x.stock<=x.min?'red':''}">${x.stock} ${esc(x.unit)}</span></td><td>${money(x.cost)}</td><td>${money((x.stock||0)*(x.cost||0))}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Товаров пока нет. Добавьте товары в разделе «Товары».</div>'}</div><div class="panel" style="margin-top:18px"><h2>История движений</h2>${data.movements.length?`<div class="table-wrap"><table><thead><tr><th>Дата</th><th>Товар</th><th>Операция</th><th>Изменение</th><th>Остаток</th></tr></thead><tbody>${data.movements.slice().reverse().map(x=>`<tr><td>${x.date}</td><td>${esc(x.name)}</td><td>${esc(x.type)}</td><td class="${x.delta<0?'muted':''}">${x.delta>0?'+':''}${x.delta}</td><td>${x.stock}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Движений пока нет.</div>'}</div>`,'Остатки и движения')}
function settings(){const account=data.sellerAccount,added=data.activity.filter(x=>x.type==='Добавление товара').length,deleted=data.activity.filter(x=>x.type==='Удаление товара').length;layout(`<div class="grid"><div class="panel"><h2>Доступ продавца</h2><p class="muted">Создайте логин и пароль для входа в отдельное приложение продавца.</p>${account?`<p><span class="badge">Аккаунт создан</span><br><br>Логин: <b>${esc(account.login)}</b></p><button class="btn secondary" onclick="openSellerAccount()">Изменить</button> <button class="btn danger" onclick="removeSellerAccount()">Удалить доступ</button>`:'<p class="empty">Аккаунт продавца ещё не создан.</p><button class="btn" onclick="openSellerAccount()">Создать доступ</button>'}</div><div class="panel"><h2>Статистика каталога</h2><div class="cards"><div class="card"><span class="muted">Добавлено товаров</span><div class="metric teal">${added}</div></div><div class="card"><span class="muted">Удалено товаров</span><div class="metric">${deleted}</div></div></div><p class="muted">Журнал действий хранится вместе с резервной копией и не изменяется при удалении товара.</p></div><div class="panel"><h2>Резервная копия</h2><p class="muted">Перенесите каталог, продажи, остатки, журнал и доступ продавца.</p><button class="btn" onclick="exportData()">Скачать JSON</button> <button class="btn secondary" onclick="document.querySelector('#import').click()">Загрузить JSON</button><input hidden id="import" type="file" accept=".json" onchange="importData(event)"></div><div class="panel"><h2>О приложении</h2><p><b>Skladon</b> работает офлайн и хранит данные в памяти браузера этого устройства.</p><p class="muted">Для синхронизации телефона в будущем можно подключить API, не меняя бизнес-логику.</p></div></div>`,'Настройки')}
function openSellerAccount(){const a=data.sellerAccount||{};modal(`<h2>${a.login?'Edit':'Create'} seller access</h2><p class="muted">Login: 4+ chars, password: 6+.</p><form id="seller-account-form" class="form-grid"><div class="field full"><label>Login *</label><input name="login" value="${esc(a.login||'')}" minlength="4" required autocomplete="off"></div><div class="field full"><label>Password *</label><input name="password" type="password" minlength="6" required autocomplete="new-password"></div><div class="modal-actions full"><button type="button" class="btn secondary" onclick="closeModal()">Cancel</button><button class="btn">Save</button></div></form>`);document.querySelector('#seller-account-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),login=String(f.get('login')).trim(),password=String(f.get('password'));if(login.length<4||password.length<6){alert('Check login and password length');return}data.sellerAccount={login,password};save();closeModal();render();toast('Seller access saved')}}
function removeSellerAccount(){if(confirm('Удалить доступ продавца?')){data.sellerAccount=null;save();render();toast('Доступ продавца удалён')}}
function openProduct(){modal(`<h2>Новый товар</h2><form id="product-form" class="form-grid"><div class="field full"><label>Название *</label><input name="name" required></div><div class="field"><label>Артикул *</label><input name="sku" required></div><div class="field"><label>Категория</label><select name="category"><option>Бытовые товары</option><option>Компьютерная техника</option><option>Оргтехника</option><option>Телефоны</option><option>Аксессуары</option><option>Другое</option></select></div><div class="field"><label>Вид товара</label><input name="type" placeholder="Телевизор, ноутбук, телефон"></div><div class="field"><label>Модель</label><input name="model" placeholder="Например, Samsung UE-..."></div><div class="field"><label>Единица</label><input name="unit" value="шт"></div><div class="field"><label>Цена продажи *</label><input name="price" type="number" min="0" required></div><div class="field"><label>Минимальная цена продажи</label><input name="minPrice" type="number" min="0" value="0" required></div><div class="field"><label>Себестоимость *</label><input name="cost" type="number" min="0" value="0" required></div><div class="field"><label>Начальный остаток</label><input name="stock" type="number" min="0" value="0"></div><div class="field"><label>Минимальный остаток</label><input name="min" type="number" min="0" value="0"></div><div class="modal-actions full"><button type="button" class="btn secondary" onclick="closeModal()">Отмена</button><button class="btn">Сохранить</button></div></form>`);document.querySelector('#product-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),x=Object.fromEntries(f);if(+x.price<+x.minPrice){alert('Цена продажи не может быть ниже минимальной цены.');return}const p={...x,id:'p'+Date.now(),price:+x.price,minPrice:+x.minPrice,cost:+x.cost,stock:+x.stock,min:+x.min};data.products.push(p);data.activity.push({type:'Добавление товара',date:today(),productId:p.id,name:p.name,sku:p.sku});if(p.stock)data.movements.push({date:today(),name:p.name,type:'Начальный остаток',delta:p.stock,stock:p.stock});save();closeModal();render();toast('Товар добавлен')}}
function deleteProduct(id){const p=data.products.find(x=>x.id===id);if(!p)return;if(!confirm(`Удалить товар «${p.name}» из текущего каталога? История продаж сохранится.`))return;data.products=data.products.filter(x=>x.id!==id);data.activity.push({type:'Удаление товара',date:today(),productId:p.id,name:p.name,sku:p.sku,category:p.category,model:p.model});save();render();toast('Товар удалён из каталога')}
function openMovement(id){const p=data.products.find(x=>x.id===id);modal(`<h2>Изменение остатка</h2><p><b>${esc(p.name)}</b> · текущий остаток: ${p.stock} ${p.unit}</p><form id="movement-form" class="form-grid"><div class="field"><label>Операция</label><select name="type"><option value="Приход">Приход</option><option value="Расход">Расход</option><option value="Инвентаризация">Установить остаток</option></select></div><div class="field"><label>Количество</label><input name="amount" type="number" min="0" required></div><div class="modal-actions full"><button type="button" class="btn secondary" onclick="closeModal()">Отмена</button><button class="btn">Провести</button></div></form>`);document.querySelector('#movement-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),type=f.get('type'),amount=+f.get('amount'),old=p.stock,delta=type==='Приход'?amount:type==='Расход'?-amount:amount-old;if(type==='Расход'&&amount>p.stock){alert('Недостаточно товара на складе');return}p.stock=type==='Инвентаризация'?amount:p.stock+delta;data.movements.push({date:today(),name:p.name,type,delta,stock:p.stock});save();closeModal();render();toast(`Остаток обновлён: ${old} → ${p.stock}`)}}
function openSale(){saleCart=[];modal(`<h2>Новая продажа</h2><div class="field"><label>Добавить товар</label><select id="sale-product" onchange="addSaleItem(this.value)"><option value="">Выберите товар...</option>${data.products.map(x=>`<option value="${x.id}">${esc(x.name)} — ${x.stock} ${x.unit}</option>`).join('')}</select></div><div id="sale-items" style="margin-top:16px"></div><div id="sale-total" class="sale-total">Итого: 0 сум</div><div class="field"><label><input id="sale-credit" type="checkbox" onchange="toggleDebtFields()"> Продажа в долг</label></div><div id="debt-fields" style="display:none" class="form-grid"><div class="field"><label>Имя должника *</label><input id="debt-customer" placeholder="Ф.И.О."></div><div class="field"><label>Телефон *</label><input id="debt-phone" type="tel" placeholder="+998 90 123 45 67"></div><div class="field full"><label>Адрес *</label><input id="debt-address" placeholder="Адрес проживания"></div><div class="field"><label>Дата возврата *</label><input id="debt-date" type="date" min="${isoToday()}"></div><div class="field full"><label>Примечание</label><input id="debt-note" placeholder="Дополнительная информация"></div></div><div class="modal-actions"><button class="btn secondary" onclick="closeModal()">Отмена</button><button id="complete-sale" class="btn" onclick="completeSale()" disabled>Провести продажу</button></div>`)}
function toggleDebtFields(){document.querySelector('#debt-fields').style.display=document.querySelector('#sale-credit').checked?'grid':'none'}
function addSaleItem(id){if(!id)return;const p=data.products.find(x=>x.id===id),found=saleCart.find(x=>x.id===id);if(found)found.qty++;else saleCart.push({id,qty:1});document.querySelector('#sale-product').value='';drawCart()}
function drawCart(){const el=document.querySelector('#sale-items');el.innerHTML=saleCart.length?saleCart.map(i=>{const p=data.products.find(x=>x.id===i.id);return `<div class="sale-row"><span>${esc(p.name)}<br><small class="muted">от ${money(p.minPrice)} · ${p.unit}</small></span><input type="number" min="1" max="${p.stock}" value="${i.qty}" onchange="changeQty('${i.id}',this.value)"><input type="number" min="${p.minPrice}" value="${i.price??p.price}" onchange="changePrice('${i.id}',this.value)"><button class="btn danger" onclick="removeSaleItem('${i.id}')">×</button></div>`}).join(''):'<div class="empty">Добавьте товары в продажу</div>';const total=saleCart.reduce((s,i)=>s+(i.price??data.products.find(x=>x.id===i.id).price)*i.qty,0);document.querySelector('#sale-total').textContent=`Итого: ${money(total)}`;document.querySelector('#complete-sale').disabled=!saleCart.length}
function changeQty(id,q){const i=saleCart.find(x=>x.id===id),p=data.products.find(x=>x.id===id);i.qty=Math.max(1,Math.min(+q||1,p.stock));drawCart()}function removeSaleItem(id){saleCart=saleCart.filter(x=>x.id!==id);drawCart()}
function changePrice(id,value){const i=saleCart.find(x=>x.id===id),p=data.products.find(x=>x.id===id),price=+value;if(price<p.minPrice){alert(`Минимальная цена для этого товара: ${money(p.minPrice)}`);drawCart();return}i.price=price;drawCart()}function completeSale(){if(saleCart.some(i=>i.qty>data.products.find(x=>x.id===i.id).stock)){alert('Количество превышает остаток');return}const credit=document.querySelector('#sale-credit').checked,customer=document.querySelector('#debt-customer').value.trim(),phone=document.querySelector('#debt-phone').value.trim(),address=document.querySelector('#debt-address').value.trim(),dueDate=document.querySelector('#debt-date').value;if(credit&&(!customer||!phone||!address||!dueDate)){alert('Укажите имя, телефон, адрес и дату возврата долга');return}const items=saleCart.map(i=>{const p=data.products.find(x=>x.id===i.id),price=i.price??p.price;p.stock-=i.qty;data.movements.push({date:today(),name:p.name,type:'Продажа в долг',delta:-i.qty,stock:p.stock});return {...i,name:p.name,price,cost:p.cost}}),total=items.reduce((s,i)=>s+i.price*i.qty,0),saleId=String(Date.now());data.sales.push({id:saleId,date:today(),items,total,profit:items.reduce((s,i)=>s+(i.price-i.cost)*i.qty,0),credit});if(credit)data.debts.push({id:'d'+saleId,saleId,customer,phone,address,dueDate,note:document.querySelector('#debt-note').value.trim(),amount:total,paid:false});save();closeModal();render();toast(credit?'Продажа в долг сохранена':'Продажа проведена')}
function markDebtPaid(id){const debt=data.debts.find(x=>x.id===id);if(!debt)return;debt.paid=true;debt.paidDate=today();save();render();toast('Долг отмечен как погашенный')}
function openReturn(saleId){const sale=data.sales.find(x=>x.id===saleId),returned=data.returns.filter(r=>r.saleId===saleId).reduce((m,r)=>(m[r.itemId]=(m[r.itemId]||0)+r.qty,m),{});modal(`<h2>Возврат товара</h2><p class="muted">Продажа от ${esc(sale.date)}. Остаток товара будет восстановлен.</p><form id="return-form" class="form-grid"><div class="field full"><label>Товар</label><select name="itemId">${sale.items.filter(i=>(returned[i.id]||0)<i.qty).map(i=>`<option value="${i.id}">${esc(i.name)} — доступно к возврату ${i.qty-(returned[i.id]||0)}</option>`).join('')}</select></div><div class="field"><label>Количество</label><input name="qty" type="number" min="1" required></div><div class="modal-actions full"><button type="button" class="btn secondary" onclick="closeModal()">Отмена</button><button class="btn">Оформить возврат</button></div></form>`);document.querySelector('#return-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),itemId=f.get('itemId'),qty=+f.get('qty'),item=sale.items.find(i=>i.id===itemId),already= data.returns.filter(r=>r.saleId===saleId&&r.itemId===itemId).reduce((s,r)=>s+r.qty,0);if(!item||qty<1||qty+already>item.qty){alert('Количество возврата превышает проданное');return}const product=data.products.find(p=>p.id===itemId);if(!product){alert('Товар больше не найден в каталоге');return}product.stock+=qty;data.returns.push({id:'r'+Date.now(),saleId,itemId,qty,date:today()});data.movements.push({date:today(),name:product.name,type:'Возврат товара',delta:qty,stock:product.stock});const factor=qty/item.qty;sale.total-=item.price*qty;sale.profit-=((item.price-item.cost)*qty);const debt=data.debts.find(d=>d.saleId===saleId&&!d.paid);if(debt)debt.amount=Math.max(0,debt.amount-item.price*qty);save();closeModal();render();toast('Возврат оформлен')}}
function printInventory(){const rows=data.products.map((x,i)=>`<tr><td>${i+1}</td><td>${esc(x.sku)}</td><td>${esc(x.name)}</td><td>${esc(x.category||'—')}</td><td>${x.stock} ${esc(x.unit)}</td><td>${money(x.cost)}</td><td>${money((x.stock||0)*(x.cost||0))}</td></tr>`).join(''),units=data.products.reduce((s,x)=>s+(Number(x.stock)||0),0),value=data.products.reduce((s,x)=>s+(Number(x.stock)||0)*(Number(x.cost)||0),0),win=window.open('','_blank','width=1000,height=700');if(!win){alert('Разрешите открытие всплывающих окон для сохранения PDF.');return}win.document.write(`<!doctype html><html lang="ru"><head><meta charset="utf-8"><title>Остатки товаров — Skladon</title><style>body{font-family:Arial,sans-serif;color:#18322f;padding:28px}h1{margin-bottom:4px}p{color:#5d7772}table{width:100%;border-collapse:collapse;margin-top:22px}th,td{border:1px solid #cddbd8;padding:9px;text-align:left}th{background:#e7f1ef;font-size:12px}tfoot{font-weight:bold}button{padding:10px 16px;background:#0f766e;color:#fff;border:0;border-radius:6px;cursor:pointer}@media print{button{display:none}}<\/style></head><body><button onclick="window.print()">Печать / сохранить PDF</button><h1>Skladon — общие остатки</h1><p>Дата отчёта: ${today()} · Позиций: ${data.products.length} · Всего единиц: ${units} · Себестоимость склада: ${money(value)}</p><table><thead><tr><th>№</th><th>Артикул</th><th>Товар</th><th>Категория</th><th>Остаток</th><th>Себестоимость</th><th>Стоимость</th></tr></thead><tbody>${rows}</tbody><tfoot><tr><td colspan="4">Итого</td><td>${units}</td><td></td><td>${money(value)}</td></tr></tfoot></table><script>window.onload=function(){window.print()}<\/script></body></html>`);win.document.close()}
function modal(html){const d=document.createElement('div');d.className='modal';d.id='modal';d.innerHTML=`<div class="modal-box">${html}</div>`;document.body.append(d)}function closeModal(){document.querySelector('#modal')?.remove()}function toast(t){const d=document.createElement('div');d.className='toast';d.textContent=t;document.body.append(d);setTimeout(()=>d.remove(),2500)}
function exportData(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download=`skladon-backup-${new Date().toISOString().slice(0,10)}.json`;a.click()}
function importData(e){const file=e.target.files[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!Array.isArray(x.products)||!Array.isArray(x.sales)||!Array.isArray(x.movements))throw Error();data={...x,debts:Array.isArray(x.debts)?x.debts:[],returns:Array.isArray(x.returns)?x.returns:[],activity:Array.isArray(x.activity)?x.activity:[],sellerAccount:x.sellerAccount||null};save();render();toast('Резервная копия загружена')}catch{alert('Некорректный файл резервной копии')}};r.readAsText(file)}
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});render();
