const KEY = 'skladon-data';
let data = JSON.parse(localStorage.getItem(KEY) || '{"products":[],"sales":[],"movements":[],"debts":[]}');
data.products = Array.isArray(data.products) ? data.products : [];
data.sales = Array.isArray(data.sales) ? data.sales : [];
data.movements = Array.isArray(data.movements) ? data.movements : [];
data.debts = Array.isArray(data.debts) ? data.debts : [];
data.returns = Array.isArray(data.returns) ? data.returns : [];
data.debts.forEach(d => { d.paid = d.paid === true; });
let cart = [];
let sellerAccount = data.sellerAccount || null;
const money = n => `${new Intl.NumberFormat('ru-RU',{maximumFractionDigits:0}).format(n || 0)} сум`;
const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dateText = () => new Date().toLocaleDateString('ru-RU');
const isoToday = () => new Date().toISOString().slice(0,10);
const debtStatus = d => d.dueDate < isoToday() ? 'Просрочен' : d.dueDate === isoToday() ? 'Сегодня' : 'Скоро';
function persist(){localStorage.setItem(KEY, JSON.stringify(data));}
function fillSelect(id, values, label){const el=document.querySelector('#'+id);el.innerHTML=`<option value="">${label}</option>`+values.filter(Boolean).sort().map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');el.disabled=!values.filter(Boolean).length}
function initFilters(){fillSelect('seller-category',[...new Set(data.products.map(p=>p.category))],'Все категории');updateTypes()}
function updateTypes(){const category=document.querySelector('#seller-category').value;const products=data.products.filter(p=>!category||p.category===category);fillSelect('seller-type',[...new Set(products.map(p=>p.type))],'Все виды товаров');document.querySelector('#seller-model').innerHTML='<option value="">Все модели</option>';document.querySelector('#seller-model').disabled=true;drawProducts()}
function updateModels(){const category=document.querySelector('#seller-category').value,type=document.querySelector('#seller-type').value;const products=data.products.filter(p=>(!category||p.category===category)&&(!type||p.type===type));fillSelect('seller-model',[...new Set(products.map(p=>p.model))],'Все модели');drawProducts()}
function drawProducts(){const q=document.querySelector('#seller-search').value.toLowerCase(),category=document.querySelector('#seller-category').value,type=document.querySelector('#seller-type').value,model=document.querySelector('#seller-model').value;const list=data.products.filter(p=>(!category||p.category===category)&&(!type||p.type===type)&&(!model||p.model===model)&&(p.name+' '+p.sku+' '+(p.category||'')+' '+(p.type||'')+' '+(p.model||'')).toLowerCase().includes(q));document.querySelector('#seller-products').innerHTML=list.length?list.map(p=>`<tr><td><b>${esc(p.name)}</b><br><span class="muted">${esc(p.type||'')} ${p.model?'· '+esc(p.model):''} · ${esc(p.sku)}</span></td><td>${money(p.price)}</td><td><span class="badge ${p.stock<=p.min?'red':''}">${p.stock} ${esc(p.unit)}</span></td></tr>`).join(''):'<tr><td colspan="3"><div class="empty">Товары не найдены</div></td></tr>'}
function drawReport(){const groups={};data.sales.forEach(s=>{const key=s.date||'Без даты';if(!groups[key])groups[key]={count:0,revenue:0,income:0};groups[key].count++;groups[key].revenue+=Number(s.total)||0;groups[key].income+=Number(s.profit)||0});const rows=Object.entries(groups).reverse();const revenue=rows.reduce((sum,[,x])=>sum+x.revenue,0),income=rows.reduce((sum,[,x])=>sum+x.income,0);document.querySelector('#seller-summary').innerHTML=`<div class="card"><span class="muted">Всего продаж</span><div class="metric teal">${data.sales.length}</div></div><div class="card"><span class="muted">Общая выручка</span><div class="metric">${money(revenue)}</div></div><div class="card"><span class="muted">Общий доход</span><div class="metric">${money(income)}</div></div>`;document.querySelector('#seller-report').innerHTML=rows.length?rows.map(([date,x])=>`<tr><td><b>${esc(date)}</b></td><td>${x.count}</td><td>${money(x.revenue)}</td><td>${money(x.income)}</td></tr>`).join(''):'<tr><td colspan="4"><div class="empty">Продаж пока нет</div></td></tr>'}
function drawSales(){document.querySelector('#seller-sales').innerHTML=data.sales.length?data.sales.slice().reverse().map(s=>`<tr><td>#${esc(s.id.slice(-5))}</td><td>${esc(s.date)}</td><td>${s.items.map(i=>esc(i.name)).join(', ')}</td><td>${money(s.total)}</td><td><button class="btn secondary" onclick="openReturn('${s.id}')">Возврат</button></td></tr>`).join(''):'<tr><td colspan="5"><div class="empty">Продаж пока нет</div></td></tr>'}
function openReturn(saleId){const sale=data.sales.find(x=>x.id===saleId),returned=data.returns.filter(r=>r.saleId===saleId).reduce((m,r)=>(m[r.itemId]=(m[r.itemId]||0)+r.qty,m),{});const box=document.createElement('div');box.className='modal';box.id='seller-return';box.innerHTML=`<div class="modal-box"><h2>Возврат товара</h2><p class="muted">Продажа от ${esc(sale.date)}</p><form id="seller-return-form" class="form-grid"><div class="field full"><label>Товар</label><select name="itemId">${sale.items.filter(i=>(returned[i.id]||0)<i.qty).map(i=>`<option value="${i.id}">${esc(i.name)} — доступно ${i.qty-(returned[i.id]||0)}</option>`).join('')}</select></div><div class="field"><label>Количество</label><input name="qty" type="number" min="1" required></div><div class="modal-actions full"><button type="button" class="btn secondary" onclick="closeReturn()">Отмена</button><button class="btn">Оформить возврат</button></div></form></div>`;document.body.append(box);document.querySelector('#seller-return-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),itemId=f.get('itemId'),qty=+f.get('qty'),item=sale.items.find(i=>i.id===itemId),already=data.returns.filter(r=>r.saleId===saleId&&r.itemId===itemId).reduce((s,r)=>s+r.qty,0);if(!item||qty<1||qty+already>item.qty){alert('Количество возврата превышает проданное');return}const product=data.products.find(p=>p.id===itemId);product.stock+=qty;data.returns.push({id:'r'+Date.now(),saleId,itemId,qty,date:dateText()});data.movements.push({date:dateText(),name:product.name,type:'Возврат товара',delta:qty,stock:product.stock});sale.total-=item.price*qty;sale.profit-=(item.price-item.cost)*qty;const debt=data.debts.find(d=>d.saleId===saleId&&!d.paid);if(debt)debt.amount=Math.max(0,debt.amount-item.price*qty);persist();closeReturn();drawProducts();drawReport();drawDebts();showToast('Возврат оформлен')}}
function closeReturn(){document.querySelector('#seller-return')?.remove()}
function drawDebts(){const debts=data.debts.filter(d=>d.paid!==true).sort((a,b)=>a.dueDate.localeCompare(b.dueDate));const urgent=debts.filter(d=>d.paid!==true&&d.dueDate<=isoToday());const n=document.querySelector('#debt-notification');n.textContent=urgent.length?`Внимание: ${urgent.length}`:'Нет срочных долгов';n.className=`badge ${urgent.length?'red':'warn'}`;document.querySelector('#seller-debts').innerHTML=debts.length?debts.map(d=>`<tr><td><b>${esc(d.customer)}</b></td><td>${esc(d.phone||'—')}</td><td>${esc(d.address||'—')}</td><td>${money(d.amount)}</td><td>${esc(d.dueDate)}</td><td><span class="badge ${d.dueDate<=isoToday()?'red':'warn'}">${debtStatus(d)}</span></td></tr>`).join(''):'<tr><td colspan="6"><div class="empty">Открытых долгов нет ✓</div></td></tr>'}
function showLogin(){document.querySelector('.seller-app').innerHTML=`<div class="modal" style="position:static;background:none;padding:0"><div class="modal-box" style="margin:60px auto"><h1>Вход продавца</h1><p class="muted">${sellerAccount?'Введите данные доступа, выданные администратором.':'Администратор ещё не создал доступ продавца.'}</p>${sellerAccount?`<form id="seller-login" class="form-grid"><div class="field full"><label>Логин</label><input name="login" autocomplete="username" required></div><div class="field full"><label>Пароль</label><input name="password" type="password" autocomplete="current-password" required></div><div class="modal-actions full"><button class="btn">Войти</button><a class="btn secondary" href="index.html">Панель администратора</a></div></form>`:'<a class="btn secondary" href="index.html">Открыть админ-панель</a>'}</div></div>`;document.querySelector('#seller-login')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);if(f.get('login')===sellerAccount.login&&f.get('password')===sellerAccount.password){sessionStorage.setItem('skladon-seller-auth',sellerAccount.login);location.reload()}else alert('Неверный логин или пароль')})}
function openSale(){cart=[];const box=document.createElement('div');box.className='modal';box.id='seller-modal';box.innerHTML=`<div class="modal-box"><h2>Новая продажа</h2><div class="field"><label>Добавить товар</label><select id="seller-product" onchange="addItem(this.value)"><option value="">Выберите товар...</option>${data.products.filter(p=>p.stock>0).map(p=>`<option value="${p.id}">${esc(p.name)} — ${money(p.price)} · ${p.stock} ${esc(p.unit)}</option>`).join('')}</select></div><div id="seller-items" style="margin-top:16px"></div><div id="seller-total" class="sale-total">Итого: 0 сум</div><div class="field"><label><input id="seller-credit" type="checkbox" onchange="toggleCredit()"> Продажа в долг</label></div><div id="seller-debt" class="form-grid" style="display:none"><div class="field"><label>Имя должника *</label><input id="seller-customer"></div><div class="field"><label>Телефон *</label><input id="seller-phone" type="tel" placeholder="+998 90 123 45 67"></div><div class="field full"><label>Адрес *</label><input id="seller-address"></div><div class="field"><label>Дата возврата *</label><input id="seller-due" type="date" min="${isoToday()}"></div></div><div class="modal-actions"><button class="btn secondary" onclick="closeSale()">Отмена</button><button class="btn" id="seller-complete" onclick="completeSale()" disabled>Провести продажу</button></div></div>`;document.body.append(box)}
function addItem(id){if(!id)return;const found=cart.find(x=>x.id===id);if(found)found.qty++;else cart.push({id,qty:1});document.querySelector('#seller-product').value='';drawCart()}
function drawCart(){document.querySelector('#seller-items').innerHTML=cart.length?cart.map(i=>{const p=data.products.find(x=>x.id===i.id);return `<div class="sale-row"><span>${esc(p.name)}<br><small class="muted">${money(p.price)}</small></span><input type="number" min="1" max="${p.stock}" value="${i.qty}" onchange="setQty('${i.id}',this.value)"><b>${money(p.price*i.qty)}</b><button class="btn danger" onclick="removeItem('${i.id}')">×</button></div>`}).join(''):'<div class="empty">Добавьте товары</div>';document.querySelector('#seller-total').textContent=`Итого: ${money(cart.reduce((s,i)=>s+data.products.find(p=>p.id===i.id).price*i.qty,0))}`;document.querySelector('#seller-complete').disabled=!cart.length}
function setQty(id,value){const i=cart.find(x=>x.id===id),p=data.products.find(x=>x.id===id);i.qty=Math.max(1,Math.min(Number(value)||1,p.stock));drawCart()}function removeItem(id){cart=cart.filter(x=>x.id!==id);drawCart()}function toggleCredit(){document.querySelector('#seller-debt').style.display=document.querySelector('#seller-credit').checked?'grid':'none'}
function completeSale(){if(cart.some(i=>i.qty>data.products.find(p=>p.id===i.id).stock)){alert('Недостаточно товара на складе');return}const credit=document.querySelector('#seller-credit').checked,customer=document.querySelector('#seller-customer').value.trim(),phone=document.querySelector('#seller-phone').value.trim(),address=document.querySelector('#seller-address').value.trim(),dueDate=document.querySelector('#seller-due').value;if(credit&&(!customer||!phone||!address||!dueDate)){alert('Укажите имя, телефон, адрес и дату возврата');return}const saleId=String(Date.now());const items=cart.map(i=>{const p=data.products.find(x=>x.id===i.id);p.stock-=i.qty;data.movements.push({date:dateText(),name:p.name,type:credit?'Продажа в долг':'Продажа',delta:-i.qty,stock:p.stock});return {...i,name:p.name,price:p.price,cost:p.cost}}),total=items.reduce((s,i)=>s+i.price*i.qty,0);data.sales.push({id:saleId,date:dateText(),items,total,profit:items.reduce((s,i)=>s+(i.price-i.cost)*i.qty,0),credit});if(credit)data.debts.push({id:'d'+saleId,saleId,customer,phone,address,dueDate,amount:total,paid:false});persist();closeSale();drawProducts();drawReport();drawSales();drawDebts();showToast('Продажа сохранена')}
function closeSale(){document.querySelector('#seller-modal')?.remove()}function showToast(text){const t=document.querySelector('#seller-toast');t.textContent=text;t.style.display='block';setTimeout(()=>t.style.display='none',2500)}
if(sellerAccount&&sessionStorage.getItem('skladon-seller-auth')===sellerAccount.login){initFilters();drawProducts();drawReport();drawSales();drawDebts()} else showLogin();
